In [45]:
import numpy as np
import pandas as pd

In [49]:
cols = ['SiO2', 'CaO', 'MgO', 'FeO', 'TiO2']
df = pd.DataFrame({k: v for k,v in zip(cols, np.random.rand(len(cols), 10))})
df.iloc[np.random.randint(0, 10, size=2), np.random.randint(1, len(cols), size=2)] = np.nan
print(df)

       SiO2       CaO       MgO       FeO      TiO2
0  0.475298       NaN  0.107144  0.561444  0.480161
1  0.858653  0.644664  0.057994  0.689687  0.708133
2  0.116973  0.730179  0.671093  0.583474  0.892287
3  0.352435  0.982656  0.917918  0.876342  0.794148
4  0.764697       NaN  0.006021  0.569915  0.539318
5  0.390501  0.086505  0.189624  0.919586  0.065146
6  0.355601  0.606177  0.722479  0.378245  0.446332
7  0.996604  0.665662  0.144942  0.941170  0.646824
8  0.457336  0.064027  0.958993  0.190874  0.499648
9  0.418470  0.964053  0.319611  0.312913  0.401621


In [50]:
for arr in [df.head(1).values,
            df.values,
            np.array([df.values, df.values])
           ]:
    print(nan_weighted_mean(arr))

[0.4752983         nan 0.10714356 0.56144377 0.48016055]
[0.51865681 0.59299036 0.40958174 0.60236501 0.54736166]
[[0.4752983         nan 0.10714356 0.56144377 0.48016055]
 [0.85865333 0.64466372 0.05799401 0.68968697 0.708133  ]
 [0.11697315 0.73017888 0.67109252 0.58347444 0.89228712]
 [0.35243476 0.9826564  0.91791809 0.87634181 0.79414821]
 [0.76469697        nan 0.00602052 0.5699146  0.53931776]
 [0.39050063 0.08650495 0.18962352 0.91958593 0.06514596]
 [0.35560068 0.60617661 0.72247896 0.37824474 0.44633158]
 [0.99660431 0.66566216 0.14494157 0.94117036 0.64682362]
 [0.45733588 0.06402732 0.95899329 0.19087446 0.49964813]
 [0.41847009 0.96405283 0.31961137 0.312913   0.40162065]]


C:\ProgramData\Anaconda3_64\envs\pyrolite\lib\site-packages\ipykernel_launcher.py:15: RuntimeWarning: Mean of empty slice
  from ipykernel import kernelapp as app
